### ISSUE TITLE
Update examples toward IDAES v2

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/examples-pse#109]
We can use this issue to keep track of the modifications that we'll need to apply to the examples to track the various changes introduced toward IDAES v2, updating it appropriately when a new `IDAES v2` PR is created.

Example structure (the content is likely wrong):

- [ ] IDAES/idaes-pse#773
  - [ ] Update import paths in `boiler_flowsheet_recon.ipynb`

**Comment by ksbeattie** [comment]
Closing this as there are other issues tracking this
