### ISSUE TITLE
Released examples 2.0.0a3 do not work with IDAES main

### ISSUE THREAD

**Issue by dangunter** [IDAES/examples-pse#148]
The most recent released examples are not up to date with changes in IDAES 2.0.0a3 and therefore have incorrect imports (e.g. `generic_models` instead of `models`) and arguments (use of `default=`). This is based only on looking at the HDA flowsheet in Tutorials/Basics, but it probably holds true for other examples as well. The code in main seems correct.

**Comment by ksbeattie** [comment]
Because we're in the midst of a v1 -> v2 transition, this is not unexpected.  Can you describe how you came across this?
