### ISSUE TITLE
Read the docs examples site should be taken down

### ISSUE THREAD

**Issue by dangunter** [IDAES/examples-pse#20]
To avoid confusion, the legacy RTD site at https://examples-pse.readthedocs.io/en/stable/ should be taken down, or serve only to redirect to the new maintained site at https://idaes.github.io/examples-pse/latest/

**Comment by ksbeattie** [comment]
I've removed the RTD examples-pse site/project entirely from RTDs.  I've searched all of the examples-pse repo for mention of the `examples-pse.readthedocs` and not found anything.  Hopefully this won't leave any broken links out there.
