### ISSUE TITLE
Fix broken links in top-level notebook_index.ipynb

### ISSUE THREAD

**Issue by jghouse88** [IDAES/examples-pse#49]
Noticed that almost all links to tutorials and examples seem to be broken in our `notebook_index.ipynb`. The following work: 
- `data_management_framework`
- `Pysmo_basics`
- `ALAMO_six_hump`
- `air_separation_case_study`

**Comment by ksbeattie** [comment]
I remember doing something like this before way back in https://github.com/IDAES/examples-dev/pull/138

**Comment by dangunter** [comment]
This is expected behavior, but we will re-examine the need for file renaming to try & make it easier to use notebooks either pre or post build.

**Comment by dangunter** [comment]
Moved this to #51
