### ISSUE TITLE
Broken links in tutorial notebooks

### ISSUE THREAD

**Issue by blnicho** [IDAES/examples-pse#72]
There are broken links in our tutorial notebooks that point users to specific pages in our idaes-pse readthedocs documentation. We should fix the links and figure out a way to test if the links work to make it easier to detect this in the future. I'll update this issue with a list of all the broken links that need to be fixed.

**Comment by dangunter** [comment]
There is a tool that is part of Sphinx (our documentation system), the "linkcheck" builder. The command would be: `sphinx-build -b linkcheck <src-dir> <output-dir>` (though not sure what output dir is used for). I am looking into whether that works properly once you've converted the notebooks into RST files with `python build.py -c`

**Comment by dangunter** [comment]
Update: linkcheck does seem to work. The steps are:

1) in top-level, build the docs and/or simply convert the notebooks with `python build.py -c`
2) cd to the `docs` subdirectory and run: ` sphinx-build -b linkcheck . .\_build\html`. This will list all broken links.

**Comment by dangunter** [comment]
Update 2: a better way to run is
```
cd docs
mkdir lc
sphinx-build -b linkcheck . lc
```
then the output will be in `lc/output.json` and `lc/output.txt`

**Comment by blnicho** [comment]
Related to: https://github.com/IDAES/idaes-pse/issues/389
