### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by Robbybp** [IDAES/examples-pse#99]
In the readme:

https://github.com/IDAES/examples-pse/blob/main/README.md?plain=1

The following section contains a broken link:

```
## Install

First, you need to download and install the examples locally, on your own computer.
Instructions for doing this are in the
[install instructions](https://idaes-pse.readthedocs.io/en/stable/install/index.html)
in the main IDAES-PSE toolkit documentation -- under the "Generic install"
section. That page also contains a link to more detailed help on the
options for choosing a custom installation directory.
```

The link is:

https://idaes-pse.readthedocs.io/en/stable/install/index.html

**Comment by lbianchi-lbl** [comment]
I've just pushed this change directly to `main` that fixes the broken link (once the new documentation structure becomes available under `stable`, i.e. as soon as the 1.13.0 tag is created).
